# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: extended-volume-manager \n"
"Report-Msgid-Bugs-To: info@discreete-linux.org\n"
"POT-Creation-Date: 2017-06-02 14:23+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: extvol-device-listener.py:20
msgid "Extended volume"
msgstr ""

#: extvol-device-listener.py:21
msgid ""
"This appears to be an extended Volume. Do you want to make use of the "
"settings stored therein?"
msgstr ""

#: extvol-close:14
msgid "Too many arguments."
msgstr ""

#: extvol-manager.py:60
msgid "Close extended volume"
msgstr ""

#: extvol-manager.py:62
msgid "Closes and Unmounts the selected extended Volume"
msgstr ""

#: extvolmanager.py:143
#, python-format
msgid ""
"A system error occured. The error was\n"
"\n"
"%(error)s\n"
"\n"
"Local variables:\n"
"%(vars)s"
msgstr ""

#: extvolmanager.py:191
#, python-format
msgid "Could not set permissions and/or ownership on %s"
msgstr ""

#: extvolmanager.py:368
msgid ""
"Failed to stop evolution, will skip loading evolution data from the extended "
"container!"
msgstr ""

#: extvolmanager.py:540
#, python-format
msgid ""
"Multiple virtual machines were found on %s, don't know which one to start. "
"Please start it manually."
msgstr ""

#: extvolmanager.py:544
msgid "Start Virtual Machine?"
msgstr ""

#: extvolmanager.py:545
#, python-format
msgid ""
"A virtual machine named \n"
"%s\n"
" was found. Do you want to start it?"
msgstr ""

#: extvolmanager.py:550
#, python-format
msgid ""
"An error occured trying to start the virtual machine:\n"
"%s"
msgstr ""

#: extvolmanager.py:643
msgid "Setup backup"
msgstr ""

#: extvolmanager.py:644
msgid ""
"You have not yet configured a backup for this volume yet. I can create a "
"default configuration which you can change later using the BackInTime "
"application.\n"
"You will need to create a backup volume using the volume wizard, if you have "
"not already done so.\n"
"Do you want to create a backup configuration now?"
msgstr ""

#: extvolmanager.py:657
msgid "An error occured while trying to create a default configuration."
msgstr ""

#: extvolmanager.py:661
msgid "An error occured while checking the backup configuration."
msgstr ""

#: extvolmanager.py:669
msgid "An error occured while trying to run a (last) snapshot."
msgstr ""

#: extvolmanager.py:683
msgid ""
"You seem to be opening an extended container previously created with Ubuntu "
"Privacy Remix. Please be aware of the following:\n"
"* Evolution data cannot be migrated. Please open with the old version "
"instead, make a data backup within evolution and restore it using this new "
"version.\n"
"* The password manager FPM is not supported anymore.\n"
"We now use KeePass 2 instead. FPM data will remain on the container; please "
"open it with UPR and export your passwords, then import them into KeePass "
"with Discreete Linux.\n"
"* <b>The keyring format of GnuPG has changed! Your existing keys will be "
"converted, and the old keyrings will remain in place. This means you can use "
"the keys you have right now both with UPR and Discreete Linux. But any newly "
"imported or created keys will only be usable on the system they were "
"imported/created on. Please read the manual for further details!</b>\n"
"\n"
"<b>Do you want to continue and open this extended container?</b>"
msgstr ""

#: extvolmanager.py:702
msgid "New Version"
msgstr ""

#: extvolmanager.py:714
msgid ""
"Either this is not an extended volume, or there is already another extended "
"volume mounted. There can only be one extended volume mounted at a time."
msgstr ""

#: extvolmanager.py:726
msgid "Low free space"
msgstr ""

#: extvolmanager.py:727
#, python-format
msgid ""
"There are only %(freebytes)s free on %(volume)s. This may cause problems "
"when using it as an extended volume. You should stop now, free some space "
"and then try re-opening this as an extended volume again.\n"
"\n"
"Stop now?"
msgstr ""

#: extvolmanager.py:743 extvolmanager.py:803
msgid "Please wait..."
msgstr ""

#: extvolmanager.py:744
msgid "Extended volume is being opened, please wait!"
msgstr ""

#: extvolmanager.py:778
msgid "Opening successful"
msgstr ""

#: extvolmanager.py:779
msgid "Extended volume opened successfully."
msgstr ""

#: extvolmanager.py:799
#, python-format
msgid ""
"There are still open files on %s, listed below. Please close them first.\n"
"\n"
msgstr ""

#: extvolmanager.py:803
msgid "Extended volume is being closed, please wait!"
msgstr ""

#: extvolmanager.py:845
#, python-format
msgid "Unmounting the volume at %s failed!"
msgstr ""

#: extvolmanager.py:847
msgid "Closing successful"
msgstr ""

#: extvolmanager.py:847
msgid "Extended volume closed successfully!"
msgstr ""
msgid "Extended volume listener"
msgstr ""

msgid "Listens for mounted volumes which could be extended volumes"
msgstr ""

